### PR TITLE
[#100] Support to kill individual connections & toggle listening for connections.

### PR DESCRIPTION
**Pull request by tolbertam**
This adds APIs for killing connections and enabling/disabling listening for new connections.

The API is currently pretty simple.  It exposes '/current/connections' and '/current/listener' endpoints for getting and closing existing connections and enabling and disabling new connections respectively (see docs/standalone/current-endpoint.md for more info).

### CODE REVIEW

**Comment by chbatey** [comment]
This is awesome, I was giving a live demo of stubbed c* and wiremock last week and someone asked if (i think wiremock) could be used to simulate the use case where you have a resource leak and have many half closed TCP connections.

**Comment by tolbertam** [comment]
Thanks!  It was pretty easy to hook into akka tcp to send the different close commands.  I did need to enable [pull mode](http://doc.akka.io/docs/akka/snapshot/scala/io-tcp.html#Read_Back-Pressure_with_Pull_Mode) to control whether or not to accept connections, but that seems to work pretty well, I should investigate what other implications that has.

I'm a bit unsure on the API, so would appreciate any feedback there.  I just added 'ConnectionsClient' for retrieving/closing socket connections and should complete `/server/listener/` shortly.

**Comment by tolbertam** [comment]
Is now functional and am moving on to use it for my tests.  Will come back to this later this week (unless I find more bugs of course):

1. Tests for routes
2. Firm up API
3. Parse response in DELETE /clients
4. Evaluation of impact of pull mode.

**Comment by chbatey** [comment]
Perhaps we could prefix the API with something like /live/ or /current/ as it differs from existing calls that show past activity. 

Another similar thing I'd like to add is the ability to stall queries indefinitely, have an API to see those queries and send in a request to complete them. This would be really useful for testing akka-persistence-cassandra https://github.com/krasserm/akka-persistence-cassandra/pull/69/ where we have batches we want to persist but we don't want toe execute batch N+1 until batch N has completed as we don't want it visible until N is and they are in different partitions.  

So we'd live:

/current/connections
/current/requests (or separate endpoints for queries, PS, batches etc)

WDYT?

**Comment by tolbertam** [comment]
:+1: on /current/connections, that is much more descriptive than /clients, I'll make that change.   I also like the idea of observing inflight queries and being able to complete them (successful or not).  I imagine you could do this by keeping a running mutable Map streamId <-> request on ConnectionHandler that you could request on TcpServer.

I think the thing that will be non-trivial will be communicating what a request message represents since currently the code parses data as it traverses the individual handler actors.   Maybe this would be another good justification for using scodec (#76) to parse the complete message and then make a decision to delegate to the appropriate handler or hold on to it based on configuration.  I had started [prototyping](https://github.com/tolbertam/scassandra-server/tree/scodec/codec/src) that a month ago, but didn't get very far, but can revisit it soon.

**Comment by tolbertam** [comment]
rebased

**Comment by tolbertam** [comment]
I deleted the docs/site directory since it was generated code (and it seemed the scassandra-docs repo did not include these).  I also updated mkdocs.yml to set the docs_dir to '.'.

**Comment by tolbertam** [comment]
Renamed '/server/listener' to '/current/listener'.  This seemed like a good idea since the 'listener' state seemed to appropriately fall under '/current' but it didn't dawn upon me until I started writing docs.  This simplifies the code quite a bit.

**Comment by tolbertam** [comment]
Think I have this all sorted out and ready for review!  If all looks good I can squash and merge.

**Comment by chbatey** [comment]
I wonder if we should wrap current connections in an object in case we want to add more information later on e.g C* introduces a client identifier, or connection start time, WDYT?

**Comment by chbatey** [comment]
Looks great, thanks for removing the docs site :)

**Comment by tolbertam** [comment]
+1 on wrapping /current/connections in an object.  I had originally done it this way but backed out to returning just an array for some reason.  I agree it would be nice to wrap it in an object for future possibilities.   I'll make it similar to the response payload of DELETE /current/connections where you get an object with an array in it ('closed_connections' in that case, maybe 'connections' in this case).    Easy to do, I'll push that up shortly, thanks!

**Comment by tolbertam** [comment]
Didn't dawn on me that you meant updating getConnections to return an object instead of List<InetSocketAddress>, so I did both things which seems to allow for more future expansion in both respects.  If that looks good I'll squash and merge.

**Comment by chbatey** [comment]
LGTM, awesome work

Yeah ive been bitten in the past for using collections/primitives in any public facing API. I wish I'd wrapped most things in the JSON too and then we would't have ended up with the "config" as well.

**Comment by tolbertam** [comment]
Thanks!  I'll squash and merge now

**Pull request merged**
